import React, { lazy, Suspense, useEffect } from "react";
import { NavLink, Redirect, Route, Switch } from "react-router-dom";
import "./Archives.css";
// constants
import { USER_ARCHIVES_EVENTS_ROUTE, USER_ARCHIVES_GC_ROUTE, USER_ARCHIVES_INTER_IIT_ROUTE } from "../../../constants/routes";
import { ARCHIVES_LOGO_PNG } from "../../../constants/images";
// contexts
import ArchivesContext from "../../../contexts/archivesContext";
// components
import Loader from "../../../components/loader/Loader";
import MediaSlider from "../../../components/mediaSlider/MediaSlider";
// mui
import SportsKabaddiRoundedIcon from "@mui/icons-material/SportsKabaddiRounded";
import EmojiEventsRoundedIcon from "@mui/icons-material/EmojiEventsRounded";
import RowingRoundedIcon from "@mui/icons-material/RowingRounded";
// sub pages
const ArchivesEvents = lazy(() => import("./archivesEvents/ArchivesEvents"));
const ArchivesGC = lazy(() => import("./archivesGC/ArchivesGC"));
const ArchivesInterIIT = lazy(() => import("./archivesInterIIT/ArchivesInterIIT"));
// test data
const archivesList = [
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Events", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Events", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Events", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Events", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Events", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Events", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "GC", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "GC", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "GC", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Inter IIT", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Inter IIT", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Inter IIT", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Inter IIT", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Inter IIT", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
    { title: "Archive Title", description: "Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details  Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details Archive Details ", date: new Date(), category: "Inter IIT", host: "Archive Publisher", fileURLs: ["https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_1.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_2.jpg?alt=media&token=01dd4de3-4fc4-4b0a-a8c0-d876415c27ce", "https://firebasestorage.googleapis.com/v0/b/tsg-hackathon.appspot.com/o/event_201221_3.jpg?alt=media&token=22af03eb-e4f3-4fd0-abf5-0aa58e27e75e"] },
];

const Archives = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="archives">
            <MediaSlider mediaFiles={archivesList.slice(0, 5).map(data => data.fileURLs[0])} isBgFixed isCarousel style={{ height: "70vh" }} />
            <div className="archives__shapeDivider">
                <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
                    <path d="M1200 0L0 0 598.97 114.72 1200 0z" className="shape-fill"></path>
                </svg>
            </div>
            <div className="archives__logo">
                <img src={ARCHIVES_LOGO_PNG} alt="" />
                <h1>Archives</h1>
                <p>Scroll, Explore & Stay Updated!</p>
                <p>One place where you get access to all the archives of different TSG, GC & Inter IIT events.</p>
            </div>
            <div className="archives__navLinks">
                <NavLink exact to={USER_ARCHIVES_EVENTS_ROUTE} className="archives__navLink" activeClassName="archives__activeNavLink"><SportsKabaddiRoundedIcon />Events</NavLink>
                <NavLink exact to={USER_ARCHIVES_GC_ROUTE} className="archives__navLink" activeClassName="archives__activeNavLink"><EmojiEventsRoundedIcon />GC</NavLink>
                <NavLink exact to={USER_ARCHIVES_INTER_IIT_ROUTE} className="archives__navLink" activeClassName="archives__activeNavLink"><RowingRoundedIcon />Inter IIT</NavLink>
            </div>
            <Suspense fallback={<Loader />}>
                <ArchivesContext.Provider value={{ archivesList }}>
                    <Switch>
                        <Route exact path={USER_ARCHIVES_EVENTS_ROUTE} component={ArchivesEvents} />
                        <Route exact path={USER_ARCHIVES_GC_ROUTE} component={ArchivesGC} />
                        <Route exact path={USER_ARCHIVES_INTER_IIT_ROUTE} component={ArchivesInterIIT} />
                        <Redirect to={USER_ARCHIVES_EVENTS_ROUTE} />
                    </Switch>
                </ArchivesContext.Provider>
            </Suspense>
        </div>
    );
};

export default Archives;
